#!/bin/sh

CONFIG="$HOME/.config/wofi/config"
STYLE="$HOME/.config/wofi/style.css"
COLORS="$HOME/.config/wofi/colors"

if ! pidof wofi >/dev/null; then
    wofi --show drun --conf "$CONFIG" --style "$STYLE" --color "$COLORS" &
else
    pkill wofi
fi
